Add Google OAuth

diff --git a/docker-entrypoint b/docker-entrypoint
--- a/docker-entrypoint
+++ b/docker-entrypoint
@@ -1,9 +1,10 @@
 #!/usr/bin/env bash
 
-if [ -z $SERVER_URL ]; then
-  echo "SERVER_URL required" >&2;
+if [ -z $SERVER_URL -o -z $OAUTH_URL ]; then
+  echo "SERVER_URL, OAUTH_URL required" >&2;
   exit 1;
 fi
 
 sed -ie "s#http://localhost:3000#$SERVER_URL#g" build/config.js
+sed -ie "s#http://localhost:3001#$OAUTH_URL#g" build/config.js
 nginx -g 'daemon off;'
